"""add_access_token_to_accounts

Revision ID: 91cfb0053f47
Revises: 6659601f9dec
Create Date: 2026-06-21 21:36:01.658778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cfb0053f47'
down_revision: Union[str, None] = '6659601f9dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('item_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'item_id')
    op.drop_column('accounts', 'access_token')
    # ### end Alembic commands ###
